// Generated from js/training/progressions.js and jam/js/tunes.js by
// scripts/gen-tunes.mjs. Do not edit by hand: change the web sources and
// run `node mobile_app/scripts/gen-tunes.mjs`.

package io.chordtrainer.ghostjam.core

import io.chordtrainer.ghostjam.core.StyleId.*

val TUNES: List<Tune> = listOf(
    Tune("I–vi–IV–V (50s)", listOf("I", "vi", "IV", "V"), "Pop & rock", listOf(BALLAD, REGGAE)),
    Tune("I–IV–vi–V", listOf("I", "IV", "vi", "V"), "Pop & rock", listOf(BALLAD, REGGAE)),
    Tune("vi–IV–I–V", listOf("vi", "IV", "I", "V"), "Pop & rock", listOf(BALLAD, LOFI, REGGAE)),
    Tune("I–V–vi–IV (axis)", listOf("I", "V", "vi", "IV"), "Pop & rock", listOf(BALLAD, LOFI, REGGAE)),
    Tune("I–ii–V–I", listOf("I", "ii", "V", "I"), "Pop & rock", listOf(BALLAD, REGGAE)),
    Tune("I–IV–V–IV", listOf("I", "IV", "V", "IV"), "Pop & rock", listOf(FUNK, REGGAE)),
    Tune("I–vi–ii–V", listOf("I", "vi", "ii", "V"), "Pop & rock", listOf(BALLAD, REGGAE)),
    Tune("vi–V–IV–V", listOf("vi", "V", "IV", "V"), "Pop & rock", listOf(BALLAD, REGGAE)),
    Tune("I–IV–I–V", listOf("I", "IV", "I", "V"), "Pop & rock", listOf(FUNK, REGGAE)),
    Tune("ii–V–I–vi", listOf("ii", "V", "I", "vi"), "Pop & rock", listOf(BALLAD, LOFI)),
    Tune("I–iii–vi–IV", listOf("I", "iii", "vi", "IV"), "Pop & rock", listOf(BALLAD)),
    Tune("I–IV–ii–V", listOf("I", "IV", "ii", "V"), "Pop & rock", listOf(BALLAD, REGGAE)),
    Tune("vi–IV–I–ii", listOf("vi", "IV", "I", "ii"), "Pop & rock", listOf(BALLAD, LOFI)),
    Tune("I–V–IV–V", listOf("I", "V", "IV", "V"), "Pop & rock", listOf(FUNK, REGGAE)),
    Tune("Amen", listOf("IVΔ", "IΔ"), "Jazz standards", listOf(LOFI, BOSSA, BALLAD)),
    Tune("Autumnal", listOf("ii", "V7", "viiø", "III7", "viΔ"), "Jazz standards", listOf(SWING, BOSSA)),
    Tune("Body & Soul", listOf("ii", "VI7", "ii", "V7", "IΔ", "IΔ"), "Jazz standards", listOf(BALLAD, SWING)),
    Tune("Dizzy", listOf("bvi", "bII7", "IΔ", "IΔ"), "Jazz standards", listOf(BOSSA, SWING)),
    Tune("Dogleg", listOf("vi", "ii7", "ii", "V7", "IΔ"), "Jazz standards", listOf(SWING, LOFI)),
    Tune("7-chord Dropback", listOf("ii", "V7", "IΔ", "VI7", "ii", "V7", "IΔ"), "Jazz standards", listOf(SWING)),
    Tune("Extended", listOf("vi", "ii", "V7", "IΔ"), "Jazz standards", listOf(SWING, BOSSA, LOFI)),
    Tune("Happenstance", listOf("#iv", "VII7", "IΔ", "IΔ"), "Jazz standards", listOf(SWING)),
    Tune("Long", listOf("iii", "VI7", "ii", "V7", "IΔ"), "Jazz standards", listOf(SWING, LOFI)),
    Tune("Overrun", listOf("ii", "V7", "IΔ", "IVΔ"), "Jazz standards", listOf(LOFI, BOSSA, SWING)),
    Tune("Moment's", listOf("#i", "#IV7", "ii", "V7", "IΔ", "IΔ"), "Jazz standards", listOf(SWING)),
    Tune("Night & Day", listOf("bVIΔ", "V7", "IΔ", "IΔ"), "Jazz standards", listOf(BOSSA, BALLAD, SWING)),
    Tune("Nobody's", listOf("IΔ", "III7", "viΔ"), "Jazz standards", listOf(BALLAD, LOFI)),
    Tune("Nowhere", listOf("bVI7", "V7", "IΔ", "IΔ"), "Jazz standards", listOf(BOSSA, SWING)),
    Tune("7-chord Pullback", listOf("ii", "V7", "iii", "VI7", "ii", "V7", "IΔ"), "Jazz standards", listOf(SWING)),
    Tune("Rainbow", listOf("IΔ", "III7", "IVΔ", "IVΔ"), "Jazz standards", listOf(BALLAD, LOFI)),
    Tune("Rainy", listOf("iii", "bIIIø", "ii", "V7", "IΔ", "IΔ"), "Jazz standards", listOf(BALLAD, BOSSA)),
    Tune("Satin", listOf("vi", "ii7", "bvi", "bII7", "IΔ", "IΔ"), "Jazz standards", listOf(SWING, LOFI)),
    Tune("Spring", listOf("VIIø", "III7", "ii", "V7", "IΔ", "IΔ"), "Jazz standards", listOf(SWING, BALLAD)),
    Tune("Stablemates", listOf("biii", "bVI7", "ii", "V7", "IΔ", "IΔ"), "Jazz standards", listOf(SWING)),
    Tune("Starlight", listOf("#IVø", "VII7", "iii", "VI7", "ii", "V7", "IΔ"), "Jazz standards", listOf(BALLAD, SWING)),
    Tune("Starlight N&D Variant", listOf("#IVø", "vi", "biiio", "VI7", "ii", "V7", "IΔ"), "Jazz standards", listOf(BALLAD, SWING)),
    Tune("Regular", listOf("ii", "V7", "IΔ"), "Jazz standards", listOf(SWING, BOSSA, LOFI, BALLAD)),
    Tune("Regular (minor)", listOf("iiø", "V7+9", "IΔ", "IΔ"), "Jazz standards", listOf(SWING, BOSSA, BALLAD)),
    Tune("Tension Ending", listOf("ii", "V7", "I7", "I7"), "Jazz standards", listOf(FUNK, SWING)),
    Tune("Tritone Substitution", listOf("ii", "bII7", "IΔ", "IΔ"), "Jazz standards", listOf(BOSSA, SWING)),
    Tune("Two-Goes", listOf("ii", "V7", "ii", "V7", "IΔ"), "Jazz standards", listOf(SWING, BOSSA)),
    Tune("Yardbird", listOf("iv", "bVII7", "IΔ", "IΔ"), "Jazz standards", listOf(SWING, LOFI)),
    Tune("Foggy", listOf("IΔ", "bIII7", "ii", "V7"), "Jazz turnarounds", listOf(SWING, BOSSA)),
    Tune("II 'n' Back", listOf("ii", "#iio", "iii"), "Jazz turnarounds", listOf(SWING)),
    Tune("Ladybird", listOf("IΔ", "bIII7", "bVIΔ", "bII7"), "Jazz turnarounds", listOf(SWING, BOSSA)),
    Tune("Nowhere (turnaround)", listOf("IΔ", "VI7", "bVI7", "V7"), "Jazz turnarounds", listOf(SWING)),
    Tune("Pennies", listOf("IΔ", "ii", "iii", "bIIIø", "ii", "V7"), "Jazz turnarounds", listOf(SWING)),
    Tune("POT", listOf("IΔ", "VI7", "ii", "V7"), "Jazz turnarounds", listOf(SWING, BOSSA, LOFI)),
    Tune("POT (minor)", listOf("iΔ", "viø", "iiø", "V7+9"), "Jazz turnarounds", listOf(SWING, BOSSA)),
    Tune("Rhythm", listOf("IΔ", "bIIo", "ii", "bIIIo"), "Jazz turnarounds", listOf(SWING)),
    Tune("SPOT", listOf("iii", "VI7", "ii", "V7"), "Jazz turnarounds", listOf(SWING, LOFI)),
    Tune("To IV 'n' Back", listOf("IΔ", "I7", "IVΔ", "#IVo", "IΔ"), "Jazz turnarounds", listOf(SWING)),
    Tune("To IV 'n' Hack", listOf("IΔ", "I7", "IVΔ", "VII7", "IΔ"), "Jazz turnarounds", listOf(SWING)),
    Tune("To IV 'n' Mack", listOf("IΔ", "I7", "IVΔ", "ivΔ", "IΔ"), "Jazz turnarounds", listOf(SWING, BALLAD)),
    Tune("To IV 'n' Yak", listOf("IΔ", "I7", "IVΔ", "bVII7", "IΔ"), "Jazz turnarounds", listOf(SWING, LOFI)),
    Tune("Whoopee", listOf("IΔ", "bIIo", "ii", "V7"), "Jazz turnarounds", listOf(SWING)),
    Tune("Autumn Leaves Opening", listOf("ii", "V7", "IΔ", "IVΔ", "viiø", "III7", "viΔ", "VI7"), "Bridges & endings", listOf(SWING, BOSSA)),
    Tune("Four-Star Ending", listOf("IVΔ", "#iv", "VII7", "iii", "VI7", "ii", "V7", "IΔ", "IΔ"), "Bridges & endings", listOf(SWING)),
    Tune("Honeysuckle Bridge", listOf("v", "I7", "IVΔ", "IVΔ", "vi", "II7", "ii", "V7"), "Bridges & endings", listOf(SWING)),
    Tune("ITCHY Opening", listOf("IΔ", "iii", "VI7", "ii", "#iv", "VII7"), "Bridges & endings", listOf(SWING)),
    Tune("On-Off-On Dropback", listOf("IΔ", "III7", "IΔ", "VI7"), "Bridges & endings", listOf(SWING)),
    Tune("Pennies Ending", listOf("IVΔ", "#ivo", "IΔ", "iii", "VI7", "ii", "V7", "IΔ", "IΔ"), "Bridges & endings", listOf(SWING)),
    Tune("Rhythm Bridge", listOf("vii", "III7", "iii", "VI7", "iv", "II7", "ii", "V7"), "Bridges & endings", listOf(SWING)),
    Tune("Sharp Fourpenny Ending", listOf("#ivø", "iv", "bVII7", "IΔ", "iii", "VI7", "ii", "V7", "IΔ", "IΔ"), "Bridges & endings", listOf(SWING)),
    Tune("Sixpenny Ending", listOf("vi", "iv", "bVII7", "IΔ", "iii", "VI7", "ii", "V7", "IΔ", "IΔ"), "Bridges & endings", listOf(SWING)),
    Tune("To IV 'n' Bird SPOT", listOf("IΔ", "I7", "IVΔ", "bVII7", "iii", "VI7", "ii", "V7"), "Bridges & endings", listOf(SWING)),
    Tune("Twopenny Ending", listOf("ii", "iv", "bVII7", "IΔ", "iii", "VI7", "ii", "V7", "IΔ"), "Bridges & endings", listOf(SWING)),
    Tune("Chromatic Dropback", listOf("IΔ", "VII7", "bVII7", "VI7", "ii"), "Dropbacks", listOf(SWING)),
    Tune("Dogleg (dropback)", listOf("ii", "V7", "v", "I7", "i"), "Dropbacks", listOf(SWING)),
    Tune("Dropback", listOf("IΔ", "VI7", "ii"), "Dropbacks", listOf(SWING)),
    Tune("Raindrop", listOf("iii", "bIIIo", "ii"), "Dropbacks", listOf(SWING)),
    Tune("Starlight Dropback", listOf("#iv", "VII7", "iii", "VI7", "ii"), "Dropbacks", listOf(SWING)),
    Tune("TINGLe Dropback", listOf("IΔ", "IV7", "bVII7", "VI7", "ii"), "Dropbacks", listOf(SWING)),
    Tune("TTFA Dropback", listOf("IΔ", "IV7", "iii", "VI7", "ii"), "Dropbacks", listOf(SWING)),
    Tune("Minor i–iv–V", listOf("i", "iv", "V", "i"), "Classical & Spanish", listOf(BALLAD, REGGAE)),
    Tune("Spanish cadence", listOf("i", "V7", "i"), "Classical & Spanish", listOf(BALLAD, REGGAE)),
    Tune("Phrygian dominant", listOf("i", "bII", "V7", "i"), "Classical & Spanish", listOf(BALLAD)),
    Tune("Baroque turnaround", listOf("i", "V", "iv", "V"), "Classical & Spanish", listOf(BALLAD)),
    Tune("Lament", listOf("i", "V", "bVI", "V"), "Classical & Spanish", listOf(BALLAD)),
    Tune("Pachelbel (minor)", listOf("i", "V", "bVI", "bIII", "iv", "i", "iv", "V"), "Classical & Spanish", listOf(BALLAD)),
    Tune("La Folia", listOf("i", "V", "i", "bVII", "bIII", "bVII", "i", "V"), "Classical & Spanish", listOf(BALLAD)),
    Tune("Greensleeves", listOf("i", "bIII", "bVII", "v", "i", "bIII", "V7", "i"), "Classical & Spanish", listOf(BALLAD)),
    Tune("Andalusian", listOf("i", "bVII", "bVI", "V"), "Andalusian", listOf(BALLAD, LOFI)),
    Tune("Hit the Road Jack", listOf("i", "bVII", "bVI", "V7"), "Andalusian", listOf(SWING, FUNK)),
    Tune("Stray Cat", listOf("i", "bVII", "bVI", "bVII"), "Andalusian", listOf(SWING, FUNK)),
    Tune("Pop minor", listOf("i", "bVI", "bVII"), "Minor pop & rock", listOf(BALLAD, LOFI, REGGAE)),
    Tune("Cinematic resolve", listOf("i", "bVI", "bVII", "i"), "Minor pop & rock", listOf(BALLAD)),
    Tune("Build-up", listOf("bVI", "bVII", "i"), "Minor pop & rock", listOf(BALLAD, REGGAE)),
    Tune("Epic descent", listOf("i", "bVI", "bIII", "bVII"), "Minor pop & rock", listOf(BALLAD, LOFI)),
    Tune("Mad World", listOf("i", "bIII", "iv", "i"), "Minor pop & rock", listOf(BALLAD, LOFI)),
    Tune("Smoke on the Water", listOf("i", "bIII", "IV", "i"), "Minor pop & rock", listOf(FUNK)),
    Tune("House of the Rising Sun", listOf("i", "bIII", "IV", "bVI", "i", "V"), "Minor pop & rock", listOf(BALLAD)),
    Tune("Stairway intro", listOf("i", "iΔ", "i7", "IV"), "Minor pop & rock", listOf(BALLAD, BOSSA, LOFI)),
    Tune("Dorian vamp", listOf("i", "IV"), "Modal vamps", listOf(FUNK, REGGAE, LOFI)),
    Tune("Dorian rock", listOf("i", "IV", "bIII", "bVII"), "Modal vamps", listOf(FUNK, REGGAE)),
    Tune("Modal pop minor", listOf("i", "bIII", "bVII", "IV"), "Modal vamps", listOf(REGGAE, BALLAD)),
    Tune("Phrygian colour", listOf("i", "bII", "bIII", "bII"), "Modal vamps", listOf(FUNK, BALLAD)),
    Tune("Minor ii–V–i", listOf("iiø", "V7", "i"), "Minor jazz", listOf(SWING, BOSSA, BALLAD)),
    Tune("Minor ii–V–iΔ", listOf("iiø", "V7+9", "iΔ"), "Minor jazz", listOf(BOSSA, SWING)),
    Tune("Minor turnaround", listOf("i", "bVI7", "iiø", "V7"), "Minor jazz", listOf(BOSSA, SWING)),
    Tune("Autumn Leaves cycle", listOf("iv7", "bVII7", "bIIIΔ", "bVIΔ", "iiø", "V7", "i"), "Minor jazz", listOf(SWING, BOSSA, LOFI)),
    Tune("Minor V-of-V", listOf("i", "II7", "V7", "i"), "Minor jazz", listOf(BOSSA, SWING)),
    Tune("Minor blues", listOf("i7", "iv7", "i7", "V7"), "Minor blues", listOf(SWING, FUNK)),
    Tune("Slow minor blues", listOf("i7", "iv7", "i7", "V7", "iv7", "i7"), "Minor blues", listOf(BALLAD, SWING)),
)
